### ISSUE TITLE
发布一个release apk包吧

### ISSUE THREAD

**Issue by forjustice** [yhm2046/AutoScreenshoot#1]
感恩

**Comment by yhm2046** [comment]
这个是我根据自己手机简单适配的，没有源码只能手动一点点调，就算我发apk给你运行在你手机上面也不是一个显示效果，除非你的手机跟我一个型号尺寸

**Comment by forjustice** [comment]
> 
> 
> 这个是我根据自己手机简单适配的，没有源码只能手动一点点调，就算我发apk给你运行在你手机上面也不是一个显示效果，除非你的手机跟我一个型号尺寸

嗯，您打个包发release吧，我们参考您的包

**Comment by yhm2046** [comment]
已发布，仅供测试，禁止商业及非法使用，违者自负法律责任

**Comment by forjustice** [comment]
> 
> 
> 已发布，仅供测试，禁止商业及非法使用，违者自负法律责任

老哥，安装不成功，在Android11上安装提示未安装，是不是debug的问题呀。另外，老哥的另一个YUEKANGQRCODE RN项目也能不能打包个安卓release包呢。感谢

**Comment by yhm2046** [comment]
如果是 Failure [INSTALL_FAILED_TEST_ONLY] 错误可以尝试：adb install -t *.apk
参考：https://blog.csdn.net/u011561668/article/details/78560197
YUEKANGQRCODE 不是我的项目，fork别人的

**Comment by forjustice** [comment]
> 
> 
> 如果是 Failure [INSTALL_FAILED_TEST_ONLY] 错误可以尝试：adb install -t *.apk
> 参考：https://blog.csdn.net/u011561668/article/details/78560197
> YUEKANGQRCODE 不是我的项目，fork别人的

再次感谢！
